services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    mem_limit: 6g
    cpus: 1.5
    env_file:
      .env
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ./entrypoint.dev.sh

    ports:
      - '3001:3000'
      - '3002:3001'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    depends_on:
      - typebot-db

  typebot-db:
    image: postgres:16
    mem_limit: 512m
    cpus: 0.5
    ports:
      - '5434:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'typebot'
      POSTGRES_PASSWORD: 'typebot'
volumes:
  db_data:
