version: '3.9'
services:
  typebot-db:
    image: postgres:16
    restart: always
    mem_limit: 512m
    cpus: 0.5
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    mem_limit: 1g
    cpus: 0.5
    depends_on:
      - typebot-db
    ports:
      - '3001:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    mem_limit: 512m
    cpus: 0.5
    ports:
      - '3002:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
volumes:
  db_data:
