version: '3.9'
services:
  typebot-db:
    image: postgres:16
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '512M'
          cpus: '0.50'
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
  typebot-builder:
    image: typebotio-typebot-builder
    build:
      context: .
      args:
        - SCOPE=builder
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1G'
          cpus: '0.50'
    depends_on:
      - typebot-db
    ports:
      - '3001:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
  typebot-viewer:
    image: typebotio-typebot-viewer
    build:
      context: .
      args:
        - SCOPE=viewer
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '512M'
          cpus: '0.50'
    ports:
      - '3002:3000'
    env_file: .env
volumes:
  db_data:
    name: typebotio_db_data
    external: true